export class Questions {
    public questions = [
        //Activities Section R
        {
            icon_path: "assets/icons/R_icon.png",
            data: [
                { qst: "Repair electrical things", like: false, isTouched: false },
                { qst: "Repair cars", like: false, isTouched: false },
                { qst: "Install,build or repair mechanical things", like: false, isTouched: false },
                { qst: "Take a technology education course(e.g, industrial arts, shop)", like: false, isTouched: false },
                { qst: "Take a woodworking course", like: false, isTouched: false },
                { qst: "Take a mechanics course", like: false, isTouched: false },
                { qst: "Operate heavy machinery or equipment", like: false, isTouched: false },
                { qst: "Work with hand tools", like: false, isTouched: false },
                { qst: "Set up electronic equipment", like: false, isTouched: false },
                { qst: "Repair a fence", like: false, isTouched: false },
                { qst: "Use metalworking or machine tools", like: false, isTouched: false },
                { qst: "Build things", like: false, isTouched: false },
                { qst: "Work with tools", like: false, isTouched: false },

            ],
            color: "#f1463c"
        },
        {
            icon_path: "assets/icons/I_icon.png",
            data: [   //Activities Section I
                { qst: "Read scientific books or magazine", like: false, isTouched: false },
                { qst: "Work in a research office or laboratory", like: false, isTouched: false },
                { qst: "Work on a scientific project", like: false, isTouched: false },
                { qst: "Study a scientific theory", like: false, isTouched: false },
                { qst: "Apply mathematics to practical problems", like: false, isTouched: false },
                { qst: "Take a physics course", like: false, isTouched: false },
                { qst: "Take a chemistry course", like: false, isTouched: false },
                { qst: "Take a mathematics course(e.g., algebra, statistics)", like: false, isTouched: false },
                { qst: "Take a biology course", like: false, isTouched: false },
                { qst: "Study scholarly or technical problems", like: false, isTouched: false },
                { qst: "Conduct experiments", like: false, isTouched: false },
                { qst: "Investigate the cause of a problem", like: false, isTouched: false },
                { qst: "Develop a research study", like: false, isTouched: false },
                { qst: "Find solutions to complex problems", like: false, isTouched: false },
            ],
            color: "#F7941D"
        },
        {
            icon_path: "assets/icons/A_icon.png",
            data: [   //Activities Section A
                { qst: "Sketch, draw, paint", like: false, isTouched: false },
                { qst: "Design furniture, clothing or printed materials", like: false, isTouched: false },
                { qst: "Play a musical instrument", like: false, isTouched: false },
                { qst: "Create portraits or photographs", like: false, isTouched: false },
                { qst: "Write novels or plays", like: false, isTouched: false },
                { qst: "Take a course in art or design", like: false, isTouched: false },
                { qst: "Arrange or compose music of any kind", like: false, isTouched: false },
                { qst: "Work with gifted artist, writer, or sculptor", like: false, isTouched: false },
                { qst: "Perform for others (e.g., dance, sing, act)", like: false, isTouched: false },
                { qst: "Edit a magazine or journal", like: false, isTouched: false },
                { qst: "Create graphic art", like: false, isTouched: false },
                { qst: "Write for a magazine or newspaper", like: false, isTouched: false },
                { qst: "Read or write poetry", like: false, isTouched: false },
                { qst: "Edit a book or magazine", like: false, isTouched: false },
            ],
            color: "#FFCE02"
        },
        {
            icon_path: "assets/icons/S_icon.png",
            data: [   //Activities Section S
                { qst: "Meet important educators or therapists", like: false, isTouched: false },
                { qst: "Work for a charity", like: false, isTouched: false },
                { qst: "Help others with their personal problems", like: false, isTouched: false },
                { qst: "Study juvenile delinquency", like: false, isTouched: false },
                { qst: "Read psychology articles or books", like: false, isTouched: false },
                { qst: "Take a human relations course", like: false, isTouched: false },
                { qst: "Teach children (e.g., elementary, middle, high school)", like: false, isTouched: false },
                { qst: "Teach adults", like: false, isTouched: false },
                { qst: "Work as a volunteer", like: false, isTouched: false },
                { qst: "Take care of young children", like: false, isTouched: false },
                { qst: "Take a self-improvement course", like: false, isTouched: false },
                { qst: "Help people with their physical or emotional needs", like: false, isTouched: false },
                { qst: "Work or volunteer for a non-profit organization", like: false, isTouched: false },
                { qst: "Help people with special needs", like: false, isTouched: false },
            ],
            color: "#00763F"
        },
        {
            icon_path: "assets/icons/E_icon.png",
            data: [   //Activities Section E
                { qst: "Learn strategies for business success", like: false, isTouched: false },
                { qst: "Meet important executives and leaders", like: false, isTouched: false },
                { qst: "Promote a product", like: false, isTouched: false },
                { qst: "Act as a business consultant", like: false, isTouched: false },
                { qst: "Supervise the work of others", like: false, isTouched: false },
                { qst: "Lead a group in accomplishing a goal", like: false, isTouched: false },
                { qst: "Operate or run a service or business", like: false, isTouched: false },
                { qst: "Take a course on administration or leadership", like: false, isTouched: false },
                { qst: "Give a sales pitch", like: false, isTouched: false },
                { qst: "Read business magazines or articles", like: false, isTouched: false },
                { qst: "Make important decisions", like: false, isTouched: false },
                { qst: "Serve as an officer of a group", like: false, isTouched: false },
                { qst: "Start my own business", like: false, isTouched: false },
                { qst: "Attend sales meetings or conferences", like: false, isTouched: false },
            ],
            color: "#0073A4"
        },
        {
            icon_path: "assets/icons/C_icon.png",
            data: [   //Activities Section C
                { qst: "Fill out detailed forms", like: false, isTouched: false },
                { qst: "Perform math calculations in bookkeeping or business", like: false, isTouched: false },
                { qst: "Operate office equipment (e.g., copy machine, fax, computer)", like: false, isTouched: false },
                { qst: "Keep detailed records of expenses", like: false, isTouched: false },
                { qst: "Set up a record-keeping system", like: false, isTouched: false },
                { qst: "Take an accounting course", like: false, isTouched: false },
                { qst: "Take an inventory of supplies or products", like: false, isTouched: false },
                { qst: "Check paperwork or products for errors or flaws", like: false, isTouched: false },
                { qst: "Update records or files", like: false, isTouched: false },
                { qst: "Work in an office", like: false, isTouched: false },
                { qst: "Write business letters", like: false, isTouched: false },
                { qst: "Develop an organizational system", like: false, isTouched: false },
                { qst: "Schedule and organize meetings", like: false, isTouched: false },
                { qst: "Take a bookkeeping course", like: false, isTouched: false },
            ],
            color: "#9279B7"
        },
        {
            icon_path: "assets/icons/R_icon.png",
            data: [   //Competencies Section R
                { qst: "I have used carpentry tools such as a power saw, lathe, or sander", like: false, isTouched: false },
                { qst: "I can make a scale drawing", like: false, isTouched: false },
                { qst: "I can change a car's oil or tire", like: false, isTouched: false },
                { qst: "I have used power tools such as a drill press or grinder", like: false, isTouched: false },
                { qst: "I can refinish furniture or woodwork", like: false, isTouched: false },
                { qst: "I can make simple electrical repairs", like: false, isTouched: false },
                { qst: "I can repair furniture", like: false, isTouched: false },
                { qst: "I can use many carpentry tools", like: false, isTouched: false },
                { qst: "I can make simple plumbing repairs", like: false, isTouched: false },
                { qst: "I can build simple objects with wood", like: false, isTouched: false },
                { qst: "I can paint a room", like: false, isTouched: false },
                { qst: "I can read blueprints", like: false, isTouched: false },
                { qst: "I can make simple repairs to home appliances (e.g., dishwasher, TV)", like: false, isTouched: false },
                { qst: "I have used a computerized drafting program", like: false, isTouched: false },
            ],
            color: "#F0483E"
        },
        {
            icon_path: "assets/icons/I_icon.png",
            data: [   //Competencies Section I
                { qst: "I can use formulas to solve mathematical problems", like: false, isTouched: false },
                { qst: "I can perform a scientific experiment or survey", like: false, isTouched: false },
                { qst: "I understand the half-life of a radioactive element", like: false, isTouched: false },
                { qst: "I know how to access resources to aid in solving scientific problems", like: false, isTouched: false },
                { qst: "I can describe the function of white blood cells", like: false, isTouched: false },
                { qst: "I can interpret simple chemical formulas", like: false, isTouched: false },
                { qst: "I understand why man-made satellites do not fall to earth", like: false, isTouched: false },
                { qst: "I can write a scientific report", like: false, isTouched: false },
                { qst: 'I understand the "Big Bang" theory of the universe', like: false, isTouched: false },
                { qst: "I understand the role of DNA in genetics", like: false, isTouched: false },
                { qst: "I can use a microscope", like: false, isTouched: false },
                { qst: "I understand the phases of mitosis", like: false, isTouched: false },
                { qst: "I can use a scientific calculator", like: false, isTouched: false },
                { qst: "I can solve puzzles that involve logical thinking", like: false, isTouched: false },
            ],
            color: "#F7941D"
        },
        {
            icon_path: "assets/icons/A_icon.png",
            data: [   //Competencies Section A
                { qst: "I can play a musical instrument", like: false, isTouched: false },
                { qst: "I can act in a play", like: false, isTouched: false },
                { qst: "I can paint, draw, or sculpt", like: false, isTouched: false },
                { qst: "I can arrange or compose music", like: false, isTouched: false },
                { qst: "I can design clothing", like: false, isTouched: false },
                { qst: "I write stories or poetry", like: false, isTouched: false },
                { qst: "I can write a speech", like: false, isTouched: false },
                { qst: "I can create an artistic representation of a concept or an idea", like: false, isTouched: false },
                { qst: "I can write a script", like: false, isTouched: false },
                { qst: "I can write news stories", like: false, isTouched: false },
                { qst: "I can sketch people so that they can be recognized", like: false, isTouched: false },
                { qst: "I can create graphic art", like: false, isTouched: false },
                { qst: "I can design the packaging for a product", like: false, isTouched: false },
                { qst: "I can write advertising copy", like: false, isTouched: false },
            ],
            color: "#FFCE02"
        },
        {
            icon_path: "assets/icons/S_icon.png",
            data: [   //Competencies Section S
                { qst: "I find it easy to talk with all kinds of people", like: false, isTouched: false },
                { qst: "I am good at explaining things to others", like: false, isTouched: false },
                { qst: "People seek me out to tell me their troubles", like: false, isTouched: false },
                { qst: "I am good at helping people who are upset or troubled", like: false, isTouched: false },
                { qst: "I have a good understanding of social relationships", like: false, isTouched: false },
                { qst: "I am good at teaching others", like: false, isTouched: false },
                { qst: "I am good at making people feel at ease", like: false, isTouched: false },
                { qst: "I am much better at working with people than with things or ideas", like: false, isTouched: false },
                { qst: "I can help people see situations from different perspectives", like: false, isTouched: false },
                { qst: "It is easy for me to talk to people I just met", like: false, isTouched: false },
                { qst: "I have participated in or organized charity events or benefit drives", like: false, isTouched: false },
                { qst: "I can easily read people's non-verbal cues", like: false, isTouched: false },
                { qst: "I am good at helping people plan their futures", like: false, isTouched: false },
                { qst: "I can facilitate group discussions", like: false, isTouched: false },
            ],
            color: "#00763F"
        },
        {
            icon_path: "assets/icons/E_icon.png",
            data: [   //Competencies Section E
                { qst: "I know how to be a successful leader", like: false, isTouched: false },
                { qst: "I am a good public speaker", like: false, isTouched: false },
                { qst: "I can manage a sales campaign", like: false, isTouched: false },
                { qst: "I can organize the work of others", like: false, isTouched: false },
                { qst: "I am an ambitious and assertive person", like: false, isTouched: false },
                { qst: "I am good at getting people to do things my way", like: false, isTouched: false },
                { qst: "I am a good salesperson", like: false, isTouched: false },
                { qst: "I am a good debater", like: false, isTouched: false },
                { qst: "I can be very persuasive", like: false, isTouched: false },
                { qst: "I have leadership skills", like: false, isTouched: false },
                { qst: "I am good at planning a strategy to achieve a goal", like: false, isTouched: false },
                { qst: "I can successfully negotiate a deal", like: false, isTouched: false },
                { qst: "I am good at motivating others", like: false, isTouched: false },
                { qst: "I am good at managing the work of others", like: false, isTouched: false },
            ],
            color: "#0073A4"
        },
        {
            icon_path: "assets/icons/C_icon.png",
            data: [   //Competencies Section C
                { qst: "I can file paperwork", like: false, isTouched: false },
                { qst: "I can do a lot of paperwork in a short time", like: false, isTouched: false },
                { qst: "I can accurately enter data into a computer", like: false, isTouched: false },
                { qst: "I can write business letters", like: false, isTouched: false },
                { qst: "I can perform office tasks (e.g., routing paperwork, answering the phone, typing)", like: false, isTouched: false },
                { qst: "I am a careful and orderly person", like: false, isTouched: false },
                { qst: "I can create a spreadsheet", like: false, isTouched: false },
                { qst: "I can take detailed notes during a meeting", like: false, isTouched: false },
                { qst: "I am good at getting information over the phone", like: false, isTouched: false },
                { qst: "I can use a word processing program", like: false, isTouched: false },
                { qst: "I can maintain records (e.g., inventory, employee, medical)", like: false, isTouched: false },
                { qst: "I can organize/schedule business meetings", like: false, isTouched: false },
                { qst: "I can direct/transfer phone calls", like: false, isTouched: false },
                { qst: "I can keep records of financial transactions", like: false, isTouched: false },
            ],
            color: "#9279B7"
        },
        {
            icon_path: "assets/icons/R_icon.png",
            data: [   //Occupations Section R
                { qst: "Aircraft mechanic", like: false, isTouched: false },
                { qst: "Automobile mechanic", like: false, isTouched: false },
                { qst: "Carpenter", like: false, isTouched: false },
                { qst: "Truck driver", like: false, isTouched: false },
                { qst: "Construction inspector", like: false, isTouched: false },
                { qst: "Machinist", like: false, isTouched: false },
                { qst: "Electrician", like: false, isTouched: false },
                { qst: "Farmer", like: false, isTouched: false },
                { qst: "Helicopter pilot", like: false, isTouched: false },
                { qst: "Welder", like: false, isTouched: false },
                { qst: "Forester", like: false, isTouched: false },
                { qst: "Roofer", like: false, isTouched: false },
                { qst: "Wildlife control agent", like: false, isTouched: false },
                { qst: "Plumber", like: false, isTouched: false },
            ],
            color: "#F0483E"
        },
        {
            icon_path: "assets/icons/I_icon.png",
            data: [   //Occupations Section I
                { qst: "Meteorologist", like: false, isTouched: false },
                { qst: "Biologist", like: false, isTouched: false },
                { qst: "Astronomer", like: false, isTouched: false },
                { qst: "Medical laboratory assistant", like: false, isTouched: false },
                { qst: "Anthropologist", like: false, isTouched: false },
                { qst: "Chemist", like: false, isTouched: false },
                { qst: "Botanist", like: false, isTouched: false },
                { qst: "Research assistant", like: false, isTouched: false },
                { qst: "Physicist", like: false, isTouched: false },
                { qst: "Environmental analyst", like: false, isTouched: false },
                { qst: "Surgeon", like: false, isTouched: false },
                { qst: "Pharmacist", like: false, isTouched: false },
                { qst: "Physician", like: false, isTouched: false },
                { qst: "Veterinarian", like: false, isTouched: false },
            ],
            color: "#F7941D"
        },
        {
            icon_path: "assets/icons/A_icon.png",
            data: [   //Occupations Section A
                { qst: "Musician", like: false, isTouched: false },
                { qst: "Writer", like: false, isTouched: false },
                { qst: "Actor", like: false, isTouched: false },
                { qst: "Musical arranger", like: false, isTouched: false },
                { qst: "Artist/painter", like: false, isTouched: false },
                { qst: "Composer", like: false, isTouched: false },
                { qst: "Sculptor", like: false, isTouched: false },
                { qst: "Web developer/designer", like: false, isTouched: false },
                { qst: "Illustrator", like: false, isTouched: false },
                { qst: "Photojournalist", like: false, isTouched: false },
                { qst: "Graphic artist/designer", like: false, isTouched: false },
                { qst: "Art instructor", like: false, isTouched: false },
                { qst: "Film/video editor", like: false, isTouched: false },
                { qst: "Lyricist", like: false, isTouched: false },
            ],
            color: "#FFCE02"
        },
        {
            icon_path: "assets/icons/S_icon.png",
            data: [   //Occupations Section S
                { qst: "Career counselor", like: false, isTouched: false },
                { qst: "School teacher", like: false, isTouched: false },
                { qst: "Substance abuse counselor", like: false, isTouched: false },
                { qst: "Speech-language pathologist", like: false, isTouched: false },
                { qst: "Marriage and family therapist", like: false, isTouched: false },
                { qst: "Clinical psychologist", like: false, isTouched: false },
                { qst: "Camp counselor", like: false, isTouched: false },
                { qst: "Social worker", like: false, isTouched: false },
                { qst: "Academic advisor", like: false, isTouched: false },
                { qst: "Physical therapist", like: false, isTouched: false },
                { qst: "Vocational rehabilitation counselor", like: false, isTouched: false },
                { qst: "Nanny", like: false, isTouched: false },
                { qst: "Recreation worker", like: false, isTouched: false },
                { qst: "School principal", like: false, isTouched: false },
            ],
            color: "#00763F"
        },
        {
            icon_path: "assets/icons/E_icon.png",
            data: [   //Occupations Section E
                { qst: "Buyer", like: false, isTouched: false },
                { qst: "Manufacturer's representative", like: false, isTouched: false },
                { qst: "Chief executive", like: false, isTouched: false },
                { qst: "Salesperson", like: false, isTouched: false },
                { qst: "Real estate sales agent", like: false, isTouched: false },
                { qst: "Retail store manager", like: false, isTouched: false },
                { qst: "Sales manager", like: false, isTouched: false },
                { qst: "Program director(TV)", like: false, isTouched: false },
                { qst: "Entrepreneur", like: false, isTouched: false },
                { qst: "Financial manager", like: false, isTouched: false },
                { qst: "Estate planner", like: false, isTouched: false },
                { qst: "Hotel/motel manager", like: false, isTouched: false },
                { qst: "Marketing executive/director", like: false, isTouched: false },
                { qst: "Financial planner", like: false, isTouched: false },
            ],
            color: "#0073A4"
        },
        {
            icon_path: "assets/icons/C_icon.png",
            data: [   //Occupations Section C
                { qst: "Bookkeeper", like: false, isTouched: false },
                { qst: "Accountant", like: false, isTouched: false },
                { qst: "Bank teller", like: false, isTouched: false },
                { qst: "Tax preparer", like: false, isTouched: false },
                { qst: "Financial analyst", like: false, isTouched: false },
                { qst: "Budget Clerk", like: false, isTouched: false },
                { qst: "Accounting/collections clerk", like: false, isTouched: false },
                { qst: "Auditor", like: false, isTouched: false },
                { qst: "Receptionist", like: false, isTouched: false },
                { qst: "Cashier", like: false, isTouched: false },
                { qst: "File clerk", like: false, isTouched: false },
                { qst: "Customer service representative", like: false, isTouched: false },
                { qst: "Court clerk", like: false, isTouched: false },
                { qst: "Medical records technician", like: false, isTouched: false },
            ],
            color: "#9279B7"
        },


    ];
}